include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    avoid_dynamic_calls: ignore
    use_build_context_synchronously: ignore
    prefer_if_elements_to_conditional_expressions: ignore
