name: ai_quiz_checker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  #State
  flutter_bloc: ^8.1.6

  #Caching
  shared_preferences: ^2.3.2

  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.14.0

  #Core
  kartal: ^4.1.0
  equatable: ^2.0.5

  #Route
  auto_route: ^9.2.2
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  json_serializable: ^6.8.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0
  mobx_codegen: ^2.6.2
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
